// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wine.Infa.EFModel.Models;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateOnly OrderDate { get; set; }

    public decimal TotalMoney { get; set; }

    public int StateId { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual State State { get; set; }
}