// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wine.Infa.EFModel.Models;

public partial class OrderItem
{
    public int Id { get; set; }

    public int ProductsId { get; set; }

    public int ProductCount { get; set; }

    public decimal ProductsPrice { get; set; }

    public decimal TotalMoney { get; set; }

    public int OrderId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Products { get; set; }
}