// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wine.Infa.EFModel.Models;

public partial class Origin
{
    public int Id { get; set; }

    public string Origin1 { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}