// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wine.Infa.EFModel.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string StaffAccount { get; set; }

    public string StaffPassword { get; set; }
}